### ISSUE TITLE
capdctl setup needs Cluster CRD

### ISSUE THREAD

**Issue by amy** [kubernetes-sigs/cluster-api-provider-docker#17]
Running `capdctl setup` doesn't work out of the box. The Cluster CRD needs to be added if it does not already exist.

```
amyc-a01:cluster-api-provider-docker amy$ capdctl setup
Error: error loading config: decoding failure: no kind "Cluster" is registered for version "kind.sigs.k8s.io/v1alpha3" in scheme "sigs.k8s.io/kind/pkg/cluster/config/encoding/scheme.go:34"
panic: exit status 1

goroutine 1 [running]:
main.makeManagementCluster(0x17138a4, 0x4)
	/Users/amy/cluster-api-provider-docker/cmd/capdctl/main.go:186 +0x188
main.main()
	/Users/amy/cluster-api-provider-docker/cmd/capdctl/main.go:82 +0x6cb
```

**Comment by chuckha** [comment]
Can you paste the command & the output/error you got?

**Comment by chuckha** [comment]
I can't reproduce on master, could you rebuild capdctl and try again? is possible you're using an older version?

**Comment by amy** [comment]
@chuckha Fetched and rebased. Still getting the same issue
