### ISSUE TITLE
Delete of DockerMachine if related DockerCluster is not present results in an NPE

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-docker#222]
/kind bug

**What steps did you take and what happened:**
- create a single control plane cluster
- delete cluster
- cascading delete of DockerMachine causes NPE because load balancer is already deleted

Resulting error:
```
I0822 15:40:32.585109       1 kind.go:176] controllers/DockerMachine/machine-actions/delete-control-plane "level"=0 "msg"="Deleting node" "cluster"="test-d" "cluster-name"="test-d" "machine"="test-d" "node-name"="test-d" 
E0822 15:40:33.339377       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190704094733-8f6ac2502e51/pkg/util/runtime/runtime.go:76
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190704094733-8f6ac2502e51/pkg/util/runtime/runtime.go:65
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190704094733-8f6ac2502e51/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/go/pkg/mod/sigs.k8s.io/kind@v0.4.0/pkg/cluster/nodes/node.go:60
/go/pkg/mod/sigs.k8s.io/kind@v0.4.0/pkg/cluster/nodes/node.go:65
/go/pkg/mod/sigs.k8s.io/kind@v0.4.0/pkg/cluster/nodes/node.go:242
/workspace/docker/actions/cluster_actions.go:88
/workspace/docker/actions/kind.go:180
/workspace/docker/nodes.go:94
/workspace/controllers/dockermachine_controller.go:252
/workspace/controllers/dockermachine_controller.go:111
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-rc.0/pkg/internal/controller/controller.go:216
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-rc.0/pkg/internal/controller/controller.go:192
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-rc.0/pkg/internal/controller/controller.go:171
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190704094733-8f6ac2502e51/pkg/util/wait/wait.go:152
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190704094733-8f6ac2502e51/pkg/util/wait/wait.go:153
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190704094733-8f6ac2502e51/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xef8227]

goroutine 360 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190704094733-8f6ac2502e51/pkg/util/runtime/runtime.go:58 +0x105
panic(0x13df3c0, 0x2375340)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
sigs.k8s.io/kind/pkg/cluster/nodes.(*Node).Cmder(...)
	/go/pkg/mod/sigs.k8s.io/kind@v0.4.0/pkg/cluster/nodes/node.go:60
sigs.k8s.io/kind/pkg/cluster/nodes.(*Node).Command(...)
	/go/pkg/mod/sigs.k8s.io/kind@v0.4.0/pkg/cluster/nodes/node.go:65
sigs.k8s.io/kind/pkg/cluster/nodes.(*Node).WriteFile(0x0, 0x157c1b1, 0x15, 0xc00073a0f0, 0xe7, 0x23aaef8, 0x0)
	/go/pkg/mod/sigs.k8s.io/kind@v0.4.0/pkg/cluster/nodes/node.go:242 +0xc7
sigs.k8s.io/cluster-api-provider-docker/docker/actions.ConfigureLoadBalancer(0xc0005d4fa0, 0x6, 0x1, 0x0)
	/workspace/docker/actions/cluster_actions.go:88 +0x658
sigs.k8s.io/cluster-api-provider-docker/docker/actions.(*MachineActions).DeleteControlPlane(0xc000259da0, 0xc0005d4fa0, 0x6, 0xc0005c1e70, 0x6, 0xc000259d90, 0xc000259d80)
	/workspace/docker/actions/kind.go:180 +0x591
sigs.k8s.io/cluster-api-provider-docker/docker.(*Node).Delete(0xc0002ed3b0, 0x6, 0xc0005c1e70)
	/workspace/docker/nodes.go:94 +0x24c
sigs.k8s.io/cluster-api-provider-docker/controllers.(*DockerMachineReconciler).reconcileDelete(0xc00036cba0, 0x179f420, 0xc0001502a0, 0xc0009ea300, 0xc000185b80, 0xc000813040, 0xc0004b9b08, 0xc0004b9d70, 0xc0005c1e80, 0x7)
	/workspace/controllers/dockermachine_controller.go:252 +0x250
sigs.k8s.io/cluster-api-provider-docker/controllers.(*DockerMachineReconciler).Reconcile(0xc00036cba0, 0xc00090cd50, 0x7, 0xc00090cdd0, 0x6, 0x238d300, 0x0, 0x0, 0x0)
	/workspace/controllers/dockermachine_controller.go:111 +0xc5e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002f20a0, 0x142df80, 0xc0005750c0, 0x142df00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-rc.0/pkg/internal/controller/controller.go:216 +0x146
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002f20a0, 0xc0003b5000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-rc.0/pkg/internal/controller/controller.go:192 +0xb5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0002f20a0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-rc.0/pkg/internal/controller/controller.go:171 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000101c80)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190704094733-8f6ac2502e51/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000101c80, 0x3b9aca00, 0x0, 0xc0006b3801, 0xc00012a120)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190704094733-8f6ac2502e51/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000101c80, 0x3b9aca00, 0xc00012a120)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190704094733-8f6ac2502e51/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-rc.0/pkg/internal/controller/controller.go:157 +0x311
```

**What did you expect to happen:**
No NPE when deleting DockerMachine

**Environment:**

- capd-manager version (use `kubectl -n docker-provider-system get pods/docker-provider-controller-manager-0 -ojsonpath='{.status.containerStatuses[0].image}{"\n"}{.status.containerStatuses[0].imageID}{"\n"}'`): latest 
- Kubernetes version (use `kubectl version`): v1.15.0

**Comment by ashish-amarnath** [comment]
I think this should no longer be an issue considering this https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/cluster_controller.go#L171 from upstream capi.

**Comment by chuckha** [comment]
/assign @chuckha 

gonna try to repro this, it may have been fixed upstream
